import '../../public/fonts/GeneralSans_Complete/Fonts/WEB/css/general-sans.css'
import '../../public/fonts/TrenchSlab_Complete/Fonts/WEB/css/trench-slab.css'

import '../../public/css/bootstrap.min.css'
import '../../public/css/colors.css'
import '../../public/scss/main.scss'
import '../../public/scss/main.scss'

import type { Metadata } from 'next'
import Head from 'next/head'
import { Inter } from 'next/font/google'
import generateColorsCss from '@/utils/colors'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Head>
        <style>{generateColorsCss()}</style>
      </Head>

      <body className={inter.className}>{children}</body>
    </html>
  )
}
