name: Build and Test PRs

on:
  pull_request:
    branches:
      - main

jobs:
  test_and_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: c-hive/gha-yarn-cache@v1

      - uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run linter
        run: yarn lint

      - name: Build
        run: yarn build
        env:
          NODE_ENV: production
